on:
  pull_request:
    branches: [ "*" ]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      # - name: Install Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.12"
          channel: 'stable'

      - name: Get dependencies
        working-directory: ostorlab_insecure_flutter_app
        run: flutter pub get

      - name: Run Unitest
        working-directory: ostorlab_insecure_flutter_app
        run: flutter test lib/tests/bug_rules_unit_test.dart

      - name: Start IPA build
        working-directory: ostorlab_insecure_flutter_app
        run: flutter build ipa --no-sound-null-safety --no-codesign

      -name: Release
        working-directory: ostorlab_insecure_flutter_app
        uses: softprops/action-gh-release@v1
        with:
          tag_name: android-v3-${{env.SNAPSHOT_HASH}}
          files: |
            lib/*.dart
            /build/ios/ipa/*
